/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AccountDAO;
import javax.swing.JOptionPane;
import model.AccountModel;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author pc
 */
public class CapNhatTaiKhoan extends javax.swing.JFrame {
    private TaiKhoanForm returnAcc;

    /**
     * Creates new form CapNhatTaiKhoan
     * @param returnAcc
     */
    public CapNhatTaiKhoan(TaiKhoanForm returnAcc) {
        initComponents();
        this.returnAcc = returnAcc;
        AccountModel acc = returnAcc.getAccountSelect();
        idTxt.setText(Integer.toString(acc.getId()));
        fullNameTxt.setText(acc.getFullName());
        userNameTxt.setText(acc.getUserName());
        userNameTxt.setEditable(false);
        emailTxt.setText(acc.getEmail());
//        passwordTxt.setText(acc.getPassword());
        roleCb.setSelectedItem(acc.getRole());
        statusCb.setSelectedItem(acc.getStatus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fullNameTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        idTxt = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        roleCb = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        statusCb = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(157, 236, 233));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 364, 20));

        jPanel7.setBackground(new java.awt.Color(194, 238, 194));

        jLabel12.setText("Vai trò");

        jLabel14.setText("Email");

        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });

        jLabel15.setText("Tên đăng nhập");

        jLabel16.setText("Tên tài khoản");

        idTxt.setEnabled(false);

        btnSave.setBackground(new java.awt.Color(35, 210, 64));
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(243, 33, 60));
        btnCancel.setText("Hủy");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        roleCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lí kho", "Nhân viên", " " }));

        jLabel17.setText("Trạng thái");

        statusCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoạt động", "Đã khóa" }));

        jLabel13.setText("ID");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(68, 68, 68)
                .addComponent(btnCancel)
                .addGap(81, 81, 81))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(statusCb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel12)
                        .addComponent(jLabel14)
                        .addComponent(jLabel16)
                        .addComponent(jLabel15)
                        .addComponent(userNameTxt)
                        .addComponent(emailTxt)
                        .addComponent(idTxt)
                        .addComponent(roleCb, 0, 172, Short.MAX_VALUE)
                        .addComponent(fullNameTxt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roleCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 364, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(idTxt.getText());
            String fullName = fullNameTxt.getText();
            String userName = userNameTxt.getText();
            String email = emailTxt.getText();
            String password = BCrypt.hashpw(idTxt.getText(), BCrypt.gensalt());  
            String role = roleCb.getSelectedItem().toString();
            int status;
            String selectedStatus = (String) statusCb.getSelectedItem();
            if (selectedStatus.equals("Hoạt động")) {
                status = 1;
            } else if (selectedStatus.equals("Đã khóa")) {
                status = 0;
            } else {
                // Xử lý trường hợp không xác định được
                status = 0; // hoặc một giá trị mặc định khác
            }
            if (!fullName.isEmpty() && !userName.isEmpty() && !email.isEmpty() && !password.isEmpty() && !role.isEmpty()) {
                    if (isValid(email)) {
                        AccountDAO accDAO1 = new AccountDAO();
                        AccountModel acc = new AccountModel(fullName, userName, password, role, status , email, id);
                        accDAO1.update(acc);
                        JOptionPane.showMessageDialog(this, "Cập nhật tài khoản thành công");
                        this.dispose();
                        AccountDAO accDAO2 = new AccountDAO();
                        returnAcc.loadDataToTable(accDAO2.selectAll()); // loadDataToTable method should be public
                    } else {
                        JOptionPane.showMessageDialog(this, "Email nhập không đúng định dạng!");
                }
            } else {                        
                JOptionPane.showMessageDialog(this, "Hãy điền đầy đủ thông tin!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    static boolean isValid(String email) {
        String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        return email.matches(regex);
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> roleCb;
    private javax.swing.JComboBox<String> statusCb;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
