/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package view;

/**
 *
 * @author pc
 */
public class NhapHangForm extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer NhapHangForm
     */
    public NhapHangForm() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblSanPham4 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        txtSoLuong4 = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        txtSearch4 = new javax.swing.JTextField();
        btnReset4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtMaPhieu4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cboNhaCungCap4 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txtNguoiTao4 = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblNhapHang4 = new javax.swing.JTable();
        btnNhapHang4 = new javax.swing.JButton();
        deleteProduct8 = new javax.swing.JButton();
        deleteProduct9 = new javax.swing.JButton();
        btnNhapExcel = new javax.swing.JButton();
        btnSuaSoLuong = new javax.swing.JButton();
        btnXoaSP = new javax.swing.JButton();
        bntNhapHang = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 520));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        tblSanPham4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane9.setViewportView(tblSanPham4);

        jLabel21.setText("Số lượng");

        txtSoLuong4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoLuong4.setText("1");

        btnAdd.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group Thêm1.png"))); // NOI18N
        btnAdd.setBorder(null);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        txtSearch4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearch4KeyReleased(evt);
            }
        });

        btnReset4.setText("Làm mới");
        btnReset4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Tìm kiếm icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReset4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel19Layout.createSequentialGroup()
                        .addComponent(txtSearch4)
                        .addGap(1, 1, 1))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        btnHome.setBackground(new java.awt.Color(255, 204, 0));
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group Trang chủ1.png"))); // NOI18N
        btnHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnHome)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtSoLuong4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnAdd))
                    .addComponent(btnHome))
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jPanel20.setBackground(new java.awt.Color(0, 204, 102));
        jPanel20.setMinimumSize(new java.awt.Dimension(630, 520));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Mã phiếu nhập");
        jPanel20.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        txtMaPhieu4.setEditable(false);
        txtMaPhieu4.setEnabled(false);
        txtMaPhieu4.setFocusable(false);
        jPanel20.add(txtMaPhieu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 150, 36));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Nhà cung cấp");
        jPanel20.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jPanel20.add(cboNhaCungCap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 150, 36));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Người tạo phiếu");
        jPanel20.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        txtNguoiTao4.setEditable(false);
        jPanel20.add(txtNguoiTao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 150, 36));

        tblNhapHang4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane10.setViewportView(tblNhapHang4);

        jPanel20.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 440, 290));

        btnNhapHang4.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnNhapHang4.setForeground(new java.awt.Color(255, 255, 255));
        btnNhapHang4.setText("Nhập hàng");
        btnNhapHang4.setBorder(null);
        btnNhapHang4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhapHang4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHang4ActionPerformed(evt);
            }
        });
        jPanel20.add(btnNhapHang4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 690, 123, 37));

        deleteProduct8.setText("Xoá sản phẩm ");
        deleteProduct8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteProduct8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProduct8ActionPerformed(evt);
            }
        });
        jPanel20.add(deleteProduct8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 160, 40));

        deleteProduct9.setText("Nhập excel");
        deleteProduct9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteProduct9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProduct9ActionPerformed(evt);
            }
        });
        jPanel20.add(deleteProduct9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, 40));

        btnNhapExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group Nhập excel1.png"))); // NOI18N
        btnNhapExcel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNhapExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel20.add(btnNhapExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 100, 40));

        btnSuaSoLuong.setBackground(new java.awt.Color(0, 204, 102));
        btnSuaSoLuong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group Chỉnh sửa1.png"))); // NOI18N
        btnSuaSoLuong.setBorder(null);
        jPanel20.add(btnSuaSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, 50));

        btnXoaSP.setBackground(new java.awt.Color(255, 51, 0));
        btnXoaSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group Xóa1.png"))); // NOI18N
        jPanel20.add(btnXoaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, 40));

        bntNhapHang.setBackground(new java.awt.Color(255, 255, 0));
        bntNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Group nhập hàng1.png"))); // NOI18N
        jPanel20.add(bntNhapHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 51, 0));
        jLabel27.setText("Tổng tiền:");
        jPanel20.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 453, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSearch4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearch4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch4KeyReleased

    private void btnReset4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReset4ActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnNhapHang4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHang4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhapHang4ActionPerformed

    private void deleteProduct8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProduct8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteProduct8ActionPerformed

    private void deleteProduct9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProduct9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteProduct9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntNhapHang;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnNhapExcel;
    private javax.swing.JButton btnNhapHang4;
    private javax.swing.JButton btnReset4;
    private javax.swing.JButton btnSuaSoLuong;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JComboBox<String> cboNhaCungCap4;
    private javax.swing.JButton deleteProduct8;
    private javax.swing.JButton deleteProduct9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tblNhapHang4;
    private javax.swing.JTable tblSanPham4;
    private javax.swing.JTextField txtMaPhieu4;
    private javax.swing.JTextField txtNguoiTao4;
    private javax.swing.JTextField txtSearch4;
    private javax.swing.JTextField txtSoLuong4;
    // End of variables declaration//GEN-END:variables
}
